name:                setoid
version:             0.1.0.0
synopsis:            A Haskell implementation of setoid
description:         Setoid (<https://en.wikipedia.org/wiki/Setoid>) is a set
                     equipped with an equivalence relation. Setoid is a useful
                     data structure in cases where equivalence is chosen not
                     to be equality. One can use it to influence the memberships
                     of the elements more strictly, as opposed to sets, and run
                     computations on unions when conflicts between elements are
                     found.

                     You can find more deatails in `Data.Setoid`
license:             BSD3
author:              Pavlo Kerestey
maintainer:          kerestey@global.de
copyright:           Global Access Internet Services GmbH
category:            Data
build-type:          Simple
extra-source-files:
- changelog.md
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5 && < 0.6

library:
  source-dirs: src
  ghc-options:      -Wall -O2

tests:
  setoid-test:
    source-dirs:      tests
    main:             RunTests.hs
    ghc-options:      -Wall -threaded  -rtsopts -with-rtsopts=-N -O
    dependencies:
      - mtl
      - setoid
      - smallcheck
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
      - tasty-smallcheck
