name:                setoid
version:             0.1.0.0
synopsis:            A Haskell implementation of setoid
description:         Setoid (https://en.wikipedia.org/wiki/Setoid) is a set
                     equipped with an equivalence relation. Mostly, one would
                     chose equivalence to be not the same as equality. This
                     makes it more strict regarding membership of elements as
                     compared to set. For full description, please see
                     documentation of Data.Setoid
license:             BSD3
author:              Pavlo Kerestey
maintainer:          kerestey@global.de
copyright:           Global Access Internet Services GmbH
category:            Data
build-type:          Simple
extra-source-files:
- changelog.md
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers

library:
  source-dirs: src
  ghc-options:      -Wall -Werror -O2

tests:
  setoid-test:
    source-dirs:      tests
    main:             RunTests.hs
    ghc-options:      -Wall -threaded  -rtsopts -with-rtsopts=-N -O
    dependencies:
      - mtl
      - setoid
      - smallcheck
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
      - tasty-smallcheck
