version: 2
jobs:
  test-8.2.2:
    docker:
      - image: fpco/stack-build:lts-11 # because library/haskell does not have 8.2.2 yet
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-ghc-8.2.2-{{ arch }}-{{ checksum "stack-8.2.2.yaml" }}
      - run: stack test
      - save_cache:
          key: stack-ghc-8.2.2-{{ arch }}-{{ checksum "stack-8.2.2.yaml" }}
          paths:
            - /root/.stack

workflows:
  version: 2
  test:
    jobs:
      - test-8.2.2